version: '3'
services:

  #PHP Service
  hami-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: hami-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - app-volume::/var/www/hami-server
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - hami-network
  #Composer Service
  hami-composer:
    container_name: hami-composer
    image: composer
    volumes:
      - app-volume:/app
    command: composer install
    networks:
      - hami-network
  #Nginx Service
  hami-webserver:
    image: nginx:alpine
    container_name: hami-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/hami-server/public
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - hami-network

  #MySQL Service
  hami-db:
    image: mysql:5.7.22
    container_name: hami-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hami-server
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql::/data/application/init.sql
    networks:
      - hami-network
  #PhpMyAdmin Service
  hami-pma:
    image: phpmyadmin/phpmyadmin
    container_name: hami-pma
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    environment:
      PMA_HOSTS: hami-db
    networks:
      - hami-network
  #tinode Service
  tinode:
    image: tinode/tinode-mysql:latest
    container_name: tinode
    restart: unless-stopped
    tty: true
    ports:
      - "8080:6060"
    environment: 
      EXT_CONFIG: ./conf/tinode.conf
    volumes:
      - ./tinode/:/opt/tinode/conf
    networks:
      - hami-network
#Docker Networks
networks:
  hami-network:
    driver: bridge
#Volumes
volumes:
  app-volume:
